repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: run-pytest
        name: Run unit tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

      - id: run-integration-tests
        name: Run integration tests
        entry: ./bin/run_api_integration_test.sh
        language: script
        types: [python]
        pass_filenames: false
