services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentlabs_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      CONFIG_YAML: config.docker.yml
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: talentlabs
      DATABASE_URL: postgres://admin:admin@timescaledb:5432/talentlabs
    networks:
      - talentlabs_network

  timescaledb:
    container_name: talentlabs_timescaledb
    image: timescale/timescaledb:2.19.2-pg15
    environment:
      POSTGRES_DB: talentlabs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_CONFIG_MAX_LOCKS_PER_TRANSACTION: "128"
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - talentlabs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d talentlabs && psql -U admin -d talentlabs -c 'SELECT 1'"]
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 10s

networks:
  talentlabs_network:
    driver: bridge
