services:
  timescaledb_test:
    container_name: job_platform_timescaledb_test
    image: timescale/timescaledb:2.19.2-pg15
    environment:
      POSTGRES_DB: job_platform_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - test_timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d job_platform_test && psql -U admin -d job_platform_test -c 'SELECT 1'"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

volumes:
  test_timescaledb_data: