services:

  timescaledb:
    container_name: talentlabs_timescaledb
    image: timescale/timescaledb:2.19.2-pg15
    environment:
      POSTGRES_DB: talentlabs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_CONFIG_MAX_LOCKS_PER_TRANSACTION: "128"
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - talentlabs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d talentlabs && psql -U admin -d talentlabs -c 'SELECT 1'"]
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 10s

networks:
  talentlabs_network:
    driver: bridge
