services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_platform_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      CONFIG_YAML: config.docker.yml
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: job_platform
      DATABASE_URL: postgres://admin:admin@timescaledb:5432/job_platform
    networks:
      - job_platform_network

  timescaledb:
    container_name: job_platform_timescaledb
    image: timescale/timescaledb:2.19.2-pg15
    environment:
      POSTGRES_DB: job_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_CONFIG_MAX_LOCKS_PER_TRANSACTION: "128"
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - job_platform_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d job_platform && psql -U admin -d job_platform -c 'SELECT 1'"]
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 10s

networks:
  job_platform_network:
    name: job_platform_network
    driver: bridge
