# Generated by Django 5.2.1 on 2025-05-25 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDBModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('salary_range', models.JSONField()),
                ('company_name', models.CharField(max_length=255)),
                ('posting_date', models.DateField(db_index=True)),
                ('expiration_date', models.DateField(db_index=True)),
                ('required_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('scheduled', 'Scheduled')], db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'job_post',
            },
        ),
    ]
