# Generated by Django 5.2.1 on 2025-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.JSONField()),
                ('company_name', models.CharField(max_length=255)),
                ('posting_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('required_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('scheduled', 'Scheduled')], max_length=20)),
            ],
        ),
    ]
